### ISSUE TITLE
Can not get printer options, when se a non-drive installed printer

### ISSUE THREAD

**Issue by Dyinfalse** [MatteoMeil/node-native-printer#10]
![image](https://user-images.githubusercontent.com/21263676/51449907-3df8d500-1d69-11e9-8cf5-74d8f367567d.png)

**Comment by Dyinfalse** [comment]
The error means that the printer name is invalid, I can't get a valid printer name, or I don't support the connection method of my printer in the bottom layer.

Please help me answer

**Comment by MatteoMeil** [comment]
Sorry for a long period of absence due to a lot of work and study.
I will take a look at this soon.

Anyway, try to escape properly backslashes and retry.

Are you using a printer shared from another PC? I.E. a server?

**Comment by MatteoMeil** [comment]
At the moment is not possible to get options or print directly using network path, that's why I've just added `feature request` label.
I'm working on to implement this possibility but you always need to add printer in Control Panel, so Windows and this package will know that the printer exists (and will show in `listPrinters()`) and they can use it as a network printer.
